name = "telegram-tempmail"
main = "src/main.js"
compatibility_date = "2026-04-18"
workers_dev = true

[vars]
DOMAIN = "example.com"

[[kv_namespaces]]
binding = "STATE_KV"
id = "REPLACE_WITH_KV_NAMESPACE_ID"
